### ISSUE TITLE
Api keys doesn't accepted

### ISSUE THREAD

**Issue by NeophyteGeek** [joshhighet/bebop#21]
I give the api keys of shodan, zoomeye and other sites but it didn't accepted ......if you could tell me the correct way to sync them it would a big help for me...

**Comment by joshhighet** [comment]
please share more info so I can understand and help? where are you running it, how are you running it, what are your executions args etc.

**Comment by NeophyteGeek** [comment]
![image](https://github.com/user-attachments/assets/ca458e84-c021-446e-97e6-171715dbd10a)

this is showing when I tried to enter the API key(I didn't put the original api key in this pic but it remains the same when I put it correct). I think I made a mistake in command. I even tried to change the key manually in your code but it didn't work.

**Comment by joshhighet** [comment]
ref #22 Zoomeye is not working, I need to update a few things.

The rest should be operational. Use an actual Onion URL, obfuscate your actual secrets, run things - and let me know if others (shodan, census etc) work (with the output if possible)

**Comment by NeophyteGeek** [comment]
![image](https://github.com/user-attachments/assets/10ab7bb8-502e-40e3-a14d-8c5f7afbc722)

shodan shows me also the same and the other functionalities might be working properly.... I faced the issue in api keys for now...

**Comment by joshhighet** [comment]
ok- try set your env as the keys? or preface your command with the required env?

i.e for your screenshot,

`SHODAN_API_KEY=123 python3 -m app xxx.onion`

**Comment by NeophyteGeek** [comment]
It didn't work for both censys and shodan.....Can you verify it once????....and send me the commands you run in your terminal...?
